name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools
        pip3 install --upgrade setuptools
        pip3 install wheel

    - name: Build package
      run: python3 setup.py sdist bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@e777b33388fefa46ce597d8afa9c15a5357af36f
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
