name: Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools
        pip3 install --upgrade setuptools
        pip3 install wheel twine

    - name: Build package
      run: python3 setup.py sdist bdist_wheel

    - name: Twine check
      run: python3 -m twine check dist/*

  lint-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools
        pip3 install --upgrade setuptools
        pip3 install flake8 black

    - name: Lint Python
      run: python3 -m flake8 canonicalwebteam tests setup.py && python3 -m black --line-length 79 --check canonicalwebteam tests setup.py

  test-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools
        pip3 install --upgrade setuptools
        pip3 install coverage

    - name: Test Python
      run: python3 -m coverage run ./setup.py test
      
  check-inclusive-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail-on-error: true
